<a href="https://colab.research.google.com/github/jeffheaton/app_deep_learning/blob/main/t81_558_class_02_2_pandas_cat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="In Colab öffnen"/></a>

# T81-558: Anwendungen tiefer neuronaler Netzwerke

**Modul 2: Python für maschinelles Lernen**

- Dozent: [Jeff Heaton](https://sites.wustl.edu/jeffheaton/), McKelvey School of Engineering, [Jeff Heaton](https://sites.wustl.edu/jeffheaton/)
– Weitere Informationen finden Sie unter [class website](https://sites.wustl.edu/jeffheaton/t81-558/).

# Modul 2 Material

Hauptvideovorlesung:

- Teil 2.1: Einführung in Pandas [[Video]](https://www.youtube.com/watch?v=wixHCvnvnsU&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=wixHCvnvnsU&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- **Teil 2.2: Kategorische Werte** [[Video]](https://www.youtube.com/watch?v=Fm7Ax23hDP0&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=Fm7Ax23hDP0&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- Teil 2.3: Gruppieren, Sortieren und Mischen in Python Pandas [[Video]](https://www.youtube.com/watch?v=tUhaD8xWd7k&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=tUhaD8xWd7k&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- Teil 2.4: Verwenden von Apply und Map in Pandas [[Video]](https://www.youtube.com/watch?v=YNo_mg1RrkM&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=YNo_mg1RrkM&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)
- Teil 2.5: Feature Engineering in Pandas für Deep Learning in PyTorch [[Video]](https://www.youtube.com/watch?v=ezaVtM405Qs&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi) [[Video]](https://www.youtube.com/watch?v=ezaVtM405Qs&list=PLjy4p-07OYzuy_lHcRW8lPTLPTTOmUpmi)

# Google CoLab-Anweisungen

Der folgende Code stellt sicher, dass Google CoLab die richtige Version von TensorFlow ausführt.

In [1]:
try:
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

Note: using Google CoLab

# Teil 2.2: Kategoriale und kontinuierliche Werte

Neuronale Netzwerke benötigen als Eingabe eine feste Anzahl von Spalten. Dieses Eingabeformat ist Tabellendaten sehr ähnlich; es muss vollständig numerisch sein. Es ist wichtig, die Daten so darzustellen, dass das neuronale Netzwerk damit trainieren kann. Bevor wir uns bestimmte Möglichkeiten zur Vorverarbeitung von Daten ansehen, ist es wichtig, vier grundlegende Datentypen zu berücksichtigen, wie sie durch [[Cite:stevens1946theory]](http://psychology.okstate.edu/faculty/jgrice/psyc3214/Stevens_FourScales_1946.pdf) definiert werden. Statistiker bezeichnen sie häufig als [[Cite:stevens1946theory]](http://psychology.okstate.edu/faculty/jgrice/psyc3214/Stevens_FourScales_1946.pdf):

- Zeichendaten (Zeichenfolgen)
- **Nominal** - Einzelne diskrete Elemente, keine Reihenfolge. Beispielsweise Farbe, Postleitzahl und Form.
- **Ordinalzahl** - Einzelne unterschiedliche Elemente haben eine implizite Reihenfolge. Zum Beispiel Gehaltsstufe, Berufsbezeichnung, Starbucks(tm)-Kaffeegröße (groß, vente, grande)
- Numerische Daten
- **Intervall** - Numerische Werte, kein definierter Start. Zum Beispiel Temperatur. Sie würden nie sagen: „Gestern war es doppelt so heiß wie heute.“
- **Verhältnis** - Numerische Werte, klar definierter Anfang. Zum Beispiel Geschwindigkeit. Man könnte sagen: „Das erste Auto fährt doppelt so schnell wie das zweite.“

## Kontinuierliche Werte kodieren

Eine häufige Transformation besteht darin, die Eingaben zu normalisieren. Manchmal ist es sinnvoll, numerische Eingaben in eine Standardform zu normalisieren, damit das Programm diese beiden Werte problemlos vergleichen kann. Stellen Sie sich vor, ein Freund sagt Ihnen, er habe einen Rabatt von 10 Dollar bekommen. Ist das ein gutes Geschäft? Vielleicht. Aber der Preis ist nicht normalisiert. Wenn Ihr Freund ein Auto gekauft hat, ist der Rabatt nicht so gut. Wenn Ihr Freund ein Mittagessen gekauft hat, ist das ein hervorragender Rabatt!

Prozentsätze sind eine weit verbreitete Form der Normalisierung. Wenn Ihr Freund Ihnen sagt, dass er 10 % Rabatt bekommen hat, wissen wir, dass das ein besserer Rabatt ist als 5 %. Dabei spielt es keine Rolle, wie hoch der Kaufpreis war. Eine weit verbreitete Normalisierungsmethode des maschinellen Lernens ist der Z-Score:

$$ z = \frac{x - \mu}{\sigma} $$

Um den Z-Score zu berechnen, müssen Sie auch den Mittelwert (&mu; oder $\bar{x}$) und die Standardabweichung (&sigma;) berechnen. Sie können den Mittelwert mit dieser Gleichung berechnen:

$$ \mu = \bar{x} = \frac{x_1+x_2+\cdots +x_n}{n} $$

Die Standardabweichung wird wie folgt berechnet:

$$ \sigma = \sqrt{\frac{1}{N} \sum\_{i=1}^N (x_i - \mu)^2} $$

Der folgende Python-Code ersetzt den MPG durch einen Z-Score. Autos mit durchschnittlichem MPG liegen nahe Null, über Null ist über dem Durchschnitt und unter Null ist unter dem Durchschnitt. Z-Scores von mehr als 3 über oder unter sind sehr selten; das sind Ausreißer.

In [2]:
import pandas as pd
from scipy.stats import zscore


df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=["NA", "?"]
)

set_option("display.max_columns", 7)
set_option("display.max_rows", 5)

df["mpg"] = zscore(df["mpg"])
display(df)

,mpg,cylinders,displacement,...,year,origin,name
0,-0.706439,8,307.0,...,70,1,chevrolet chevelle malibu
1,-1.090751,8,350.0,...,70,1,buick skylark 320
...,...,...,...,...,...,...,...
396,0.574601,4,120.0,...,82,1,ford ranger
397,0.958913,4,119.0,...,82,1,chevy s-10

### Kodieren kategorialer Werte als Dummies

Die traditionelle Methode zum Kodieren kategorialer Werte besteht darin, sie zu Dummyvariablen zu machen. Diese Technik wird auch One-Hot-Encoding genannt. Betrachten Sie den folgenden Datensatz.

In [3]:
df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/jh-simple-dataset.csv",
    na_values=["NA", "?"],
)

set_option("display.max_columns", 7)
set_option("display.max_rows", 5)

display(df)

        id job area  ...  retail_dense     crime  product
0        1  vv    c  ...      0.492126  0.071100        b
1        2  kd    c  ...      0.342520  0.400809        c
...    ...  ..  ...  ...           ...       ...      ...
1998  1999  qp    c  ...      0.598425  0.117803        c
1999  2000  pe    c  ...      0.539370  0.451973        c

[2000 rows x 14 columns]

Die Spalte _area_ ist nicht numerisch, daher müssen Sie sie mit One-Hot-Kodierung kodieren. Wir zeigen die Anzahl der Bereiche und Einzelwerte an. In diesem Fall gibt es in der kategorialen Variable _area_ nur vier Werte.

In [4]:
areas = list(df["area"].unique())
print(f"Anzahl der Bereiche: {len(areas)}")
print(f"Bereiche: {areas}")

Number of areas: 4
Areas: ['c', 'd', 'a', 'b']

In der Spalte _area_ gibt es vier eindeutige Werte. Um diese Dummy-Variablen zu kodieren, würden wir vier Spalten verwenden, die jeweils einen der Bereiche darstellen. Für jede Zeile hätte eine Spalte den Wert eins, der Rest Nullen. Aus diesem Grund wird diese Art der Kodierung manchmal One-Hot-Kodierung genannt. Der folgende Code zeigt, wie Sie die Werte „a“ bis „d“ kodieren könnten. Der Wert A wird zu [1,0,0,0] und der Wert B wird zu [0,1,0,0].

In [5]:
dummies = get_dummies(["a", "b", "c", "d"], prefix="area", dtype=int)
print(dummies)

   area_a  area_b  area_c  area_d
0       1       0       0       0
1       0       1       0       0
2       0       0       1       0
3       0       0       0       1

Wir können jetzt die eigentliche Spalte kodieren.

In [6]:
dummies = get_dummies(df["area"], prefix="area", dtype=int)
print(dummies[0:10])  # Zeigen Sie nur die ersten 10

    area_a  area_b  area_c  area_d
0        0       0       1       0
1        0       0       1       0
..     ...     ...     ...     ...
8        0       0       1       0
9        1       0       0       0

[10 rows x 4 columns]

Damit die neuen Dummy-/One-Hot-codierten Werte von Nutzen sind, müssen sie wieder in den Datensatz eingefügt werden.

In [7]:
df = concat([df, dummies], axis=1)

Um die Spalte _area_ zu kodieren, verwenden wir den folgenden Code. Beachten Sie, dass diese Dummies wieder in den Datenrahmen eingefügt werden müssen.

In [8]:
set_option("display.max_columns", 0)
set_option("display.max_rows", 10)

display(df[["id", "job", "area", "income", "area_a", "area_b", "area_c", "area_d"]])

        id job area   income  area_a  area_b  area_c  area_d
0        1  vv    c  50876.0       0       0       1       0
1        2  kd    c  60369.0       0       0       1       0
2        3  pe    c  55126.0       0       0       1       0
3        4  11    c  51690.0       0       0       1       0
4        5  kl    d  28347.0       0       0       0       1
...    ...  ..  ...      ...     ...     ...     ...     ...
1995  1996  vv    c  51017.0       0       0       1       0
1996  1997  kl    d  26576.0       0       0       0       1
1997  1998  kl    d  28595.0       0       0       0       1
1998  1999  qp    c  67949.0       0       0       1       0
1999  2000  pe    c  61467.0       0       0       1       0

[2000 rows x 8 columns]

Normalerweise entfernen Sie die ursprüngliche Spalte „_Bereich_“, da das Ziel darin besteht, den Datenrahmen für das neuronale Netzwerk vollständig numerisch zu gestalten.

In [9]:
set_option("display.max_columns", 0)
set_option("display.max_rows", 5)

df.drop("area", axis=1, inplace=True)
display(df[["id", "job", "income", "area_a", "area_b", "area_c", "area_d"]])

        id job   income  area_a  area_b  area_c  area_d
0        1  vv  50876.0       0       0       1       0
1        2  kd  60369.0       0       0       1       0
...    ...  ..      ...     ...     ...     ...     ...
1998  1999  qp  67949.0       0       0       1       0
1999  2000  pe  61467.0       0       0       1       0

[2000 rows x 7 columns]

### Entfernen der ersten Ebene

Die Funktion **concat** enthält auch einen Parameter namens _drop_first_, der angibt, ob durch Entfernen der ersten Ebene k-1 Dummies aus k kategorialen Ebenen entfernt werden sollen. Warum sollten Sie die erste Ebene entfernen wollen, in diesem Fall _area_a_? Diese Technik bietet eine effizientere Kodierung, indem sie die normalerweise ungenutzte Kodierung von [0,0,0] verwendet. Wir kodieren den _area_ in nur drei Spalten und ordnen den kategorischen Wert von _a_ [0,0,0] zu. Der folgende Code demonstriert diese Technik.

In [10]:
dummies = get_dummies(
    ["a", "b", "c", "d"], prefix="area", drop_first=True, dtype=int
)
print(dummies)

   area_b  area_c  area_d
0       0       0       0
1       1       0       0
2       0       1       0
3       0       0       1

Wie Sie aus den obigen Daten ersehen können, fehlt die Spalte _area_a_, da **get_dummies** sie durch die Kodierung [0,0,0] ersetzt hat. Der folgende Code zeigt, wie diese Technik auf einen Datenrahmen angewendet wird.

In [11]:
# Lesen des Datensatzes
df = read_csv(
    "https://data.heatonresearch.com/data/t81-558/jh-simple-dataset.csv",
    na_values=["NA", "?"],
)

# Kodieren Sie die Flächenspalte als Dummyvariablen
dummies = get_dummies(df["area"], drop_first=True, prefix="area")
df = concat([df, dummies], axis=1)
df.drop("area", axis=1, inplace=True)

# den codierten Datenrahmen anzeigen
set_option("display.max_columns", 0)
set_option("display.max_rows", 10)

display(df[["id", "job", "income", "area_b", "area_c", "area_d"]])

        id job   income  area_b  area_c  area_d
0        1  vv  50876.0   False    True   False
1        2  kd  60369.0   False    True   False
2        3  pe  55126.0   False    True   False
3        4  11  51690.0   False    True   False
4        5  kl  28347.0   False   False    True
...    ...  ..      ...     ...     ...     ...
1995  1996  vv  51017.0   False    True   False
1996  1997  kl  26576.0   False   False    True
1997  1998  kl  28595.0   False   False    True
1998  1999  qp  67949.0   False    True   False
1999  2000  pe  61467.0   False    True   False

[2000 rows x 6 columns]

## Zielkodierung für kategorische Werte

Zielkodierung ist eine beliebte Technik für Kaggle-Wettbewerbe. Zielkodierung kann manchmal die Vorhersagekraft eines maschinellen Lernmodells erhöhen. Allerdings erhöht sie auch das Risiko einer Überanpassung dramatisch. Aufgrund dieses Risikos müssen Sie bei der Verwendung dieser Methode vorsichtig sein.

Im Allgemeinen kann die ZielKodierung nur dann auf ein kategoriales Merkmal angewendet werden, wenn die Ausgabe des maschinellen Lernmodells numerisch ist (Regression).

Das Konzept der Zielkodierung ist unkompliziert. Für jede Kategorie berechnen wir den durchschnittlichen Zielwert für diese Kategorie. Dann ersetzen wir zum Kodieren den Prozentsatz, der der Kategorie entspricht, die der kategorische Wert hat. Im Gegensatz zu Dummyvariablen, bei denen Sie für jede Kategorie mit Zielkodierung eine Spalte haben, benötigt das Programm nur eine einzige Spalte. Auf diese Weise ist die Zielkodierung effizienter als Dummyvariablen.

In [12]:
import numpy as np

# Erstellen Sie einen kleinen Beispieldatensatz
np.random.seed(43)
df = DataFrame(
    {
        "cont_9": np.random.rand(10) * 100,
        "cat_0": ["dog"] * 5 + ["cat"] * 5,
        "cat_1": ["wolf"] * 9 + ["tiger"] * 1,
        "y": [1, 0, 1, 1, 1, 1, 0, 0, 0, 0],
    }
)

set_option("display.max_columns", 0)
set_option("display.max_rows", 0)
display(df)

      cont_9 cat_0  cat_1  y
0  11.505457   dog   wolf  1
1  60.906654   dog   wolf  0
2  13.339096   dog   wolf  1
3  24.058962   dog   wolf  1
4  32.713906   dog   wolf  1
5  85.913749   cat   wolf  1
6  66.609021   cat   wolf  0
7  54.116221   cat   wolf  0
8   2.901382   cat   wolf  0
9  73.374830   cat  tiger  0

Wir möchten sie in eine Zahl umwandeln, anstatt Dummy-Variablen für „Hund“ und „Katze“ zu erstellen. Wir möchten sie in eine Zahl umwandeln. Wir könnten 0 für eine Katze und 1 für einen Hund verwenden. Wir können jedoch mehr Informationen als nur das kodieren. Die einfache 0 oder 1 würde auch nur für ein Tier funktionieren. Überlegen Sie, was der mittlere Zielwert für Katze und Hund ist.

In [13]:
means0 = df.groupby("cat_0")["y"].mean().to_dict()
means0

{'cat': 0.2, 'dog': 0.8}

Die Gefahr besteht darin, dass wir jetzt den Zielwert ($y$) für das Training verwenden. Diese Technik führt möglicherweise zu Überanpassung. Die Möglichkeit einer Überanpassung ist noch größer, wenn eine kleine Anzahl einer bestimmten Kategorie vorhanden ist. Um dies zu verhindern, verwenden wir einen Gewichtungsfaktor. Je stärker das Gewicht, desto mehr Kategorien mit weniger Werten tendieren zum Gesamtdurchschnitt von $y$. Sie können diese Berechnung wie folgt durchführen.

In [14]:
df["y"].mean()

0.5

Sie können die Zielkodierung wie folgt implementieren. Weitere Informationen zur Zielkodierung finden Sie im Artikel ["Target Encoding Done the Right Way"](https://maxhalford.github.io/blog/target-encoding/), auf dem dieser Code basiert.

In [15]:
def calc_smooth_mean(df1, df2, cat_name, target, weight):
    # Berechnen Sie den globalen Mittelwert
    mean = df[target].mean()

    # Berechnen Sie die Anzahl der Werte und den Mittelwert jeder Gruppe
    agg = df.groupby(cat_name)[target].agg(["count", "mean"])
    counts = agg["count"]
    means = agg["mean"]

    # Berechnen Sie die „geglätteten“ Mittelwerte
    smooth = (counts * means + weight * mean) / (counts + weight)

    # Ersetzen Sie jeden Wert durch den entsprechenden geglätteten Mittelwert
    if df2 is None:
        return df1[cat_name].map(smooth)
    else:
        return df1[cat_name].map(smooth), df2[cat_name].map(smooth.to_dict())

Der folgende Code kodiert diese beiden Kategorien.

In [16]:
WEIGHT = 5
df["cat_0_enc"] = calc_smooth_mean(
    df1=df, df2=None, cat_name="cat_0", target="y", weight=WEIGHT
)
df["cat_1_enc"] = calc_smooth_mean(
    df1=df, df2=None, cat_name="cat_1", target="y", weight=WEIGHT
)

set_option("display.max_columns", 0)
set_option("display.max_rows", 0)

display(df)

      cont_9 cat_0  cat_1  y  cat_0_enc  cat_1_enc
0  11.505457   dog   wolf  1       0.65   0.535714
1  60.906654   dog   wolf  0       0.65   0.535714
2  13.339096   dog   wolf  1       0.65   0.535714
3  24.058962   dog   wolf  1       0.65   0.535714
4  32.713906   dog   wolf  1       0.65   0.535714
5  85.913749   cat   wolf  1       0.35   0.535714
6  66.609021   cat   wolf  0       0.35   0.535714
7  54.116221   cat   wolf  0       0.35   0.535714
8   2.901382   cat   wolf  0       0.35   0.535714
9  73.374830   cat  tiger  0       0.35   0.416667

## Kodierung kategorialer Werte als Ordinalzahlen

Normalerweise werden kategorische Variablen als Dummyvariablen kodiert. Es gibt jedoch möglicherweise andere Techniken, um kategorische Variablen in numerische Variablen umzuwandeln. Immer wenn die kategorischen Variablen geordnet sind, sollte eine Zahl verwendet werden. Stellen Sie sich vor, Sie hätten eine kategorische Variable, die den aktuellen Bildungsstand einer Person beschreibt.

- Kindergarten (0)
- Erste Klasse (1)
- Zweite Klasse (2)
- Dritte Klasse (3)
- Vierte Klasse (4)
- Fünfte Klasse (5)
- Sechste Klasse (6)
- Siebte Klasse (7)
- Achte Klasse (8)
- High School-Neuling (9)
- High School-Zehntklässler (10)
- Oberstufenschüler (11)
- Abiturient (12)
- College-Neuling (13)
- College-Student im zweiten Jahr (14)
- College-Junior (15)
- College-Senior (16)
- Doktorand (17)
- Doktorand (18)
- Promotion (19)
- Postdoktorat (20)

Die obige Liste hat 21 Ebenen und würde 21 Dummyvariablen zum Kodieren benötigen. Wenn man dies jedoch einfach in Dummyvariablen kodiert, geht die Reihenfolgeinformation verloren. Der vielleicht einfachste Ansatz wäre, sie einfach zu nummerieren und der Kategorie eine einzelne Zahl zuzuweisen, die dem Wert in der Klammer oben entspricht. Wir könnten es jedoch noch besser machen. Ein Doktorand ist wahrscheinlich länger als ein Jahr dabei, also könnten Sie einen Wert erhöhen.

## Hohe Kardinalität Kategorisch

Wenn es viele wären, vielleicht Tausende oder Zehntausende, dann ist One-Hot-Encoding keine gute Wahl mehr. Wir nennen diese Fälle kategorisch mit hoher Kardinalität. Wir Kodieren solche Werte im Allgemeinen mit einer Einbettungsschicht, die wir später bei der Einführung der Verarbeitung natürlicher Sprache (NLP) besprechen werden.